core_carnetadresse:
    resource: "@CoreBundle/Resources/config/routing/carnetadresse.yml"
    prefix:   /carnetadresse

core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Security:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"