<?php

namespace CoreBundle\Repository;

/**
 * CarnetAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarnetAdresseRepository extends \Doctrine\ORM\EntityRepository
{

}
